import { Theme, ThemeName } from '@/types/global';

export const themes: Record<ThemeName, Theme> = {
  'calm-blue': {
    name: 'calm-blue',
    displayName: 'Calm Blue',
    colors: {
      primary: '#3B82F6',
      primaryDark: '#2563EB',
      secondary: '#E0F2FE',
      accent: '#06B6D4',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      text: '#1E293B',
      textSecondary: '#64748B',
      border: '#E2E8F0',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#FFFFFF',
      shadow: 'rgba(59, 130, 246, 0.1)',
    },
  },
  'solar-dark': {
    name: 'solar-dark',
    displayName: 'Solar Dark',
    colors: {
      primary: '#F59E0B',
      primaryDark: '#D97706',
      secondary: '#451A03',
      accent: '#FBBF24',
      background: '#0F172A',
      surface: '#1E293B',
      text: '#F1F5F9',
      textSecondary: '#94A3B8',
      border: '#334155',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#1E293B',
      shadow: 'rgba(245, 158, 11, 0.2)',
    },
  },
  'nature-green': {
    name: 'nature-green',
    displayName: 'Nature Green',
    colors: {
      primary: '#10B981',
      primaryDark: '#059669',
      secondary: '#ECFDF5',
      accent: '#34D399',
      background: '#F7FDF7',
      surface: '#FFFFFF',
      text: '#1F2937',
      textSecondary: '#6B7280',
      border: '#D1FAE5',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#FFFFFF',
      shadow: 'rgba(16, 185, 129, 0.1)',
    },
  },
  'sunset-orange': {
    name: 'sunset-orange',
    displayName: 'Sunset Orange',
    colors: {
      primary: '#F97316',
      primaryDark: '#EA580C',
      secondary: '#FFF7ED',
      accent: '#FB923C',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      text: '#1C1917',
      textSecondary: '#78716C',
      border: '#FED7AA',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#FFFFFF',
      shadow: 'rgba(249, 115, 22, 0.1)',
    },
  },
  'minimal-white': {
    name: 'minimal-white',
    displayName: 'Minimal White',
    colors: {
      primary: '#000000',
      primaryDark: '#1F2937',
      secondary: '#F9FAFB',
      accent: '#4B5563',
      background: '#FFFFFF',
      surface: '#F9FAFB',
      text: '#111827',
      textSecondary: '#6B7280',
      border: '#E5E7EB',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#F9FAFB',
      shadow: 'rgba(0, 0, 0, 0.05)',
    },
  },
  'purple-dream': {
    name: 'purple-dream',
    displayName: 'Purple Dream',
    colors: {
      primary: '#8B5CF6',
      primaryDark: '#7C3AED',
      secondary: '#F3E8FF',
      accent: '#A78BFA',
      background: '#FDFBFF',
      surface: '#FFFFFF',
      text: '#1F2937',
      textSecondary: '#6B7280',
      border: '#E9D5FF',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#FFFFFF',
      shadow: 'rgba(139, 92, 246, 0.1)',
    },
  },
  'rose-gold': {
    name: 'rose-gold',
    displayName: 'Rose Gold',
    colors: {
      primary: '#F43F5E',
      primaryDark: '#E11D48',
      secondary: '#FFF1F2',
      accent: '#FB7185',
      background: '#FFFBFC',
      surface: '#FFFFFF',
      text: '#1F2937',
      textSecondary: '#6B7280',
      border: '#FECDD3',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#FFFFFF',
      shadow: 'rgba(244, 63, 94, 0.1)',
    },
  },
  'ocean-blue': {
    name: 'ocean-blue',
    displayName: 'Ocean Blue',
    colors: {
      primary: '#0EA5E9',
      primaryDark: '#0284C7',
      secondary: '#E0F7FA',
      accent: '#38BDF8',
      background: '#F0F9FF',
      surface: '#FFFFFF',
      text: '#1E293B',
      textSecondary: '#64748B',
      border: '#BAE6FD',
      success: '#10B981',
      warning: '#F59E0B',
      error: '#EF4444',
      card: '#FFFFFF',
      shadow: 'rgba(14, 165, 233, 0.1)',
    },
  },
};

export const defaultTheme: ThemeName = 'calm-blue';